### ISSUE TITLE
🐞 错误报告 - GPT无法给出返回后报错

### ISSUE THREAD

**Issue by A1KESH1** [ConnectAI-E/Feishu-EX-ChatGPT#12]
当ChatGPT无法回答时（控制台输出select one line: I don't know）后，出现报错。
此情况下，飞书有时候会发出来消息（但是不是正确结果，GPT会建议你自行查找），有时候没有任何返回，但是隔较长一段时间后会将正确结果发出来。

![918bef28-fc82-4352-8391-1cc112bf60d2](https://user-images.githubusercontent.com/42016325/235316490-8e01d4d8-5ab3-44e1-b7bc-a117b3b69b49.jpeg)

**Comment by xpzouying** [comment]
好的，收到，感谢反馈。

目前，增加了新的搜索引擎，如果没有配置 Google Search Token 的话，默认可以走不需要 token 的新的搜索引擎，结果如下：

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/3946563/235347298-4f1bde88-3270-4fcd-968f-db3667511c5c.png">

**Comment by A1KESH1** [comment]
是有配置Google Search的，也能正常给出答案和参考网站链接。是部分问题会出现这种情况

**Comment by xpzouying** [comment]
> 是有配置Google Search的，也能正常给出答案和参考网站链接。是部分问题会出现这种情况

有错误日志的截图，或者相关的提问参考吗？方便给我看一下吗，这样我可以理解得更加直观点。

**Comment by A1KESH1** [comment]
就是图里的那个提问，“深圳湾睿印有哪些商铺入驻了”，报错也是图里那个。飞书反应是：1.没有发送任何消息，2.或者将chatgpt的“ 很抱歉，我是AI语言模型，不知道XXX”发到飞书，3.或者给出答案
![IMG_1162](https://user-images.githubusercontent.com/42016325/235363167-2e45f9b5-fac4-4ed3-ac81-472f6b1384ef.png)

**Comment by xpzouying** [comment]
> 

目前增加部分功能可以避免这种情况，
1. 会触发搜索能力。
2. 如果搜索插件没有满足的话，会使用 chatgpt 来回答这个问题。（但是有可能 chatgpt 确实不知道结论）
