### ISSUE TITLE
🚀 功能改善 - 搜索内容自优化

### ISSUE THREAD

**Issue by A1KESH1** [ConnectAI-E/Feishu-EX-ChatGPT#13]
可以考虑借鉴langflow的思路：
第一步，只让gpt拆解用户提问，并提供给搜索API进行搜索（返回多条结果）
第二步，gpt对搜索出来的多条结果进行理解，分析与用户提问的关联度。
第三步，如果关联度较低，重新拆分并尝试自行更换搜索内容再次进行搜索。
以此类推，直到搜索结果与用户提问关联度较高。gpt概括最终返回的几个搜索结果，并发送给用户

**Comment by xpzouying** [comment]
嗯，感谢建议，是个很好的建议，后期我考虑往这上面进行一些优化。
