### ISSUE TITLE
功能增强：支持其他联网搜索引擎

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/Feishu-EX-ChatGPT#7]

**Comment by A1KESH1** [comment]
谷歌源可以考虑再支持个serper吗
![image](https://user-images.githubusercontent.com/42016325/235316445-cb28d879-8cf2-45bb-91a7-d722477f4457.png)

**Comment by xpzouying** [comment]
> 谷歌源可以考虑再支持个serper吗 ![image](https://user-images.githubusercontent.com/42016325/235316445-cb28d879-8cf2-45bb-91a7-d722477f4457.png)

可以啊，也欢迎贡献一下：https://github.com/agi-cn/llmplugin
